version: "3.7"

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/lib/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass@word
      - MSSQL_PID=Developer
    restart: unless-stopped
