version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mssql
    environment:
      MYSQL_DATABASE: db
      # So you don't have to use root, but you can if you like
      MYSQL_USER: admin
      # You can use whatever password you like
      MYSQL_PASSWORD: "0000"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "0000"
    restart: unless-stopped
