version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server /data/redis.conf
    volumes:
      - ./data:/data
      - ./data/redis.conf:/data/redis.conf
    restart: unless-stopped
